// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_url_updated_vars`, `build_analyze_url`, `insert_option_metadata`, `merge_alias`, `merge_vars_json`, `merge_vars_value`, `request_body_from_analyze_url`, `split_url_option_raw`, `take_header_ci`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AnalyzeUrlBuild`

AnalyzeUrlResult analyzeUrl({required AnalyzeUrlRequest req}) =>
    RustLib.instance.api.crateApiAnalyzeUrlAnalyzeUrl(req: req);

Future<FetchUrlResult> fetchUrl({required FetchUrlRequest req}) =>
    RustLib.instance.api.crateApiAnalyzeUrlFetchUrl(req: req);

class AnalyzeUrlRequest {
  final String url;
  final String? baseUrl;
  final int? page;
  final String? key;
  final Map<String, String>? headerMap;

  const AnalyzeUrlRequest({
    required this.url,
    this.baseUrl,
    this.page,
    this.key,
    this.headerMap,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      baseUrl.hashCode ^
      page.hashCode ^
      key.hashCode ^
      headerMap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalyzeUrlRequest &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          baseUrl == other.baseUrl &&
          page == other.page &&
          key == other.key &&
          headerMap == other.headerMap;
}

class AnalyzeUrlResult {
  final String url;
  final String method;
  final Map<String, String> headers;
  final String? body;
  final int retry;
  final bool useWebview;
  final String? webjs;
  final int webviewDelayTime;
  final String? error;

  /// Rust 侧 JS 执行后更新的变量快照
  /// 包含 cookieJar::<host> 键，供 Dart 侧同步到 PersistCookieJar
  final Map<String, String> updatedVars;

  const AnalyzeUrlResult({
    required this.url,
    required this.method,
    required this.headers,
    this.body,
    required this.retry,
    required this.useWebview,
    this.webjs,
    required this.webviewDelayTime,
    this.error,
    required this.updatedVars,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      method.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      retry.hashCode ^
      useWebview.hashCode ^
      webjs.hashCode ^
      webviewDelayTime.hashCode ^
      error.hashCode ^
      updatedVars.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalyzeUrlResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          method == other.method &&
          headers == other.headers &&
          body == other.body &&
          retry == other.retry &&
          useWebview == other.useWebview &&
          webjs == other.webjs &&
          webviewDelayTime == other.webviewDelayTime &&
          error == other.error &&
          updatedVars == other.updatedVars;
}

class FetchUrlRequest {
  final String url;
  final String? baseUrl;
  final int? page;
  final String? key;
  final Map<String, String>? headerMap;
  final bool binaryAsHex;

  const FetchUrlRequest({
    required this.url,
    this.baseUrl,
    this.page,
    this.key,
    this.headerMap,
    required this.binaryAsHex,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      baseUrl.hashCode ^
      page.hashCode ^
      key.hashCode ^
      headerMap.hashCode ^
      binaryAsHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchUrlRequest &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          baseUrl == other.baseUrl &&
          page == other.page &&
          key == other.key &&
          headerMap == other.headerMap &&
          binaryAsHex == other.binaryAsHex;
}

class FetchUrlResult {
  final String url;
  final String body;
  final int status;
  final Map<String, List<String>> headers;
  final String? error;
  final Map<String, String> updatedVars;
  final WebViewRequest? webviewRequest;

  const FetchUrlResult({
    required this.url,
    required this.body,
    required this.status,
    required this.headers,
    this.error,
    required this.updatedVars,
    this.webviewRequest,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      body.hashCode ^
      status.hashCode ^
      headers.hashCode ^
      error.hashCode ^
      updatedVars.hashCode ^
      webviewRequest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchUrlResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          body == other.body &&
          status == other.status &&
          headers == other.headers &&
          error == other.error &&
          updatedVars == other.updatedVars &&
          webviewRequest == other.webviewRequest;
}

class WebViewRequest {
  final String url;
  final String method;
  final Map<String, String> headers;
  final String? body;
  final String? webjs;
  final int webviewDelayTime;

  const WebViewRequest({
    required this.url,
    required this.method,
    required this.headers,
    this.body,
    this.webjs,
    required this.webviewDelayTime,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      method.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      webjs.hashCode ^
      webviewDelayTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebViewRequest &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          method == other.method &&
          headers == other.headers &&
          body == other.body &&
          webjs == other.webjs &&
          webviewDelayTime == other.webviewDelayTime;
}
