// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../entities/book_source.dart';
import '../entities/rules.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_content_replace`, `apply_to`, `apply_toc_format_js`, `book_item_key`, `build_path_without_encode`, `calculate_similarity`, `chinese_num_value`, `chinese_to_int`, `dedup_book_items`, `direct_capture_ref_value`, `extract_list_items_core`, `fallback_join`, `get_chapter_num`, `get_pure_chapter_name`, `get_string_list_with_captures`, `get_string_with_captures`, `has_any_key`, `has_rule_template`, `is_absolute_url`, `is_any_bracket`, `is_true_like`, `looks_like_book_source_value`, `matching_close_bracket`, `matching_open_bracket`, `normalize_book_list_rule`, `optional_str`, `remove_whitespace`, `rule_engine_base64_decode`, `rule_engine_base64_encode`, `set_book_var`, `strip_chapter_number_prefix`, `strip_edge_brackets`, `strip_leading_bracket`, `strip_trailing_bracket`, `to_json`, `toc_chapter_json`, `toc_parse_limit`, `value_first_string`, `value_to_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

String formatHtml({required String html}) =>
    RustLib.instance.api.crateApiRuleEngineFormatHtml(html: html);

int findMatchingChapter(
        {required String target, required List<String> chapterNames}) =>
    RustLib.instance.api.crateApiRuleEngineFindMatchingChapter(
        target: target, chapterNames: chapterNames);

String resolveUrl({required String base, required String href}) =>
    RustLib.instance.api.crateApiRuleEngineResolveUrl(base: base, href: href);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuleEngine>>
abstract class RuleEngine implements RustOpaqueInterface {
  static Future<RuleEngine> default_() =>
      RustLib.instance.api.crateApiRuleEngineRuleEngineDefault();

  /// Evaluate image-decode style JS with binary `result`.
  ///
  /// - `input_base64`: encrypted image bytes (standard base64)
  /// - returns decrypted bytes as standard base64, or empty string on failure
  Future<String> evalBytesJs(
      {required String script,
      required String inputBase64,
      required String baseUrl,
      String? src});

  Future<BookInfo?> extractBookInfo(
      {required String html,
      required BookInfoRule rule,
      required String baseUrl});

  Future<List<BookItem>> extractBookList(
      {required String html,
      required SearchRule rule,
      required String baseUrl});

  /// Returns a `TocResult` which includes both the chapter list and the
  /// optional next TOC page URL (for multi-page TOC, mirrors Kotlin's `nextTocUrl`).
  Future<TocResult> extractChapterList(
      {required String html, required TocRule rule, required String baseUrl});

  Future<ChapterContent?> extractContent(
      {required String html,
      required ContentRule rule,
      required String baseUrl});

  Future<List<BookItem>> extractExploreList(
      {required String html,
      required ExploreRule rule,
      required String baseUrl});

  Future<List<ReviewItem>> extractReviewList(
      {required String html,
      required ReviewRule rule,
      required String baseUrl});

  /// Apply `ruleToc.formatJs` after Dart has finished TOC pagination,
  /// de-duplication, and final ordering.
  Future<List<Chapter>> formatTocChapters(
      {required List<Chapter> chapters,
      required String formatJs,
      required List<String> baseUrls});

  Future<String> getVariable({required String key});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RuleEngine> newInstance() =>
      RustLib.instance.api.crateApiRuleEngineRuleEngineNew();

  static Future<BookSource?> parseBookSource({required String json}) =>
      RustLib.instance.api
          .crateApiRuleEngineRuleEngineParseBookSource(json: json);

  static Future<List<BookSource>> parseBookSourceList({required String json}) =>
      RustLib.instance.api
          .crateApiRuleEngineRuleEngineParseBookSourceList(json: json);

  /// Parse `BookSource.exploreUrl` into concrete kinds.
  ///
  /// Mirrors Kotlin `BookSourceExtensions.exploreKinds()` behavior:
  /// - supports `@js:` / `<js>...</js>` scripts
  /// - script result may be JSON array or `title::url` lines
  Future<List<ExploreKindItem>> parseExploreKinds({required String exploreUrl});

  Future<void> putVariable({required String key, required String value});

  /// Set the serialised Book JSON for `book.xxx` access in JS.
  Future<void> setBookJson({String? json});

  Future<void> setBookName({required String name});

  Future<void> setBookVar({required String key, required String value});

  /// Set the serialised BookChapter JSON for `chapter.xxx` access in JS.
  Future<void> setChapterJson({String? json});

  Future<void> setChapterTitle({required String title});

  Future<void> setChapterVar({required String key, required String value});

  /// Set the per-source shared JS library (BookSource.jsLib).
  Future<void> setJsLib({String? lib});

  /// Set per-source default headers used by JS `java.ajax`.
  ///
  /// The input format should be a JSON object string, e.g.
  /// `{"User-Agent":"...","Cookie":"a=1"}`.
  Future<void> setSourceHeadersJson({String? headerJson});

  Future<void> setSourceVar({required String key, required String value});

  Future<Map<String, String>> snapshotSessionVars();

  Future<Map<String, String>> snapshotSourceVars();
}

class BookInfo {
  final String name;
  final String? author;
  final String? intro;
  final String? coverUrl;
  final String? tocUrl;
  final String? kind;
  final String? lastChapter;
  final String? updateTime;
  final String? wordCount;
  final String? canReName;
  final String? downloadUrls;

  const BookInfo({
    required this.name,
    this.author,
    this.intro,
    this.coverUrl,
    this.tocUrl,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.wordCount,
    this.canReName,
    this.downloadUrls,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      coverUrl.hashCode ^
      tocUrl.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      wordCount.hashCode ^
      canReName.hashCode ^
      downloadUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          intro == other.intro &&
          coverUrl == other.coverUrl &&
          tocUrl == other.tocUrl &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          wordCount == other.wordCount &&
          canReName == other.canReName &&
          downloadUrls == other.downloadUrls;
}

class BookItem {
  final String name;
  final String? author;
  final String bookUrl;
  final String? coverUrl;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? wordCount;
  final String? updateTime;
  final String? tocUrl;

  const BookItem({
    required this.name,
    this.author,
    required this.bookUrl,
    this.coverUrl,
    this.intro,
    this.kind,
    this.lastChapter,
    this.wordCount,
    this.updateTime,
    this.tocUrl,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      bookUrl.hashCode ^
      coverUrl.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      wordCount.hashCode ^
      updateTime.hashCode ^
      tocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          bookUrl == other.bookUrl &&
          coverUrl == other.coverUrl &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          wordCount == other.wordCount &&
          updateTime == other.updateTime &&
          tocUrl == other.tocUrl;
}

class BookRuleContext {
  final String name;
  final String? author;
  final String? bookUrl;
  final String? tocUrl;
  final String? coverUrl;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? wordCount;
  final String? updateTime;
  final String? canReName;
  final String? downloadUrls;

  const BookRuleContext({
    required this.name,
    this.author,
    this.bookUrl,
    this.tocUrl,
    this.coverUrl,
    this.intro,
    this.kind,
    this.lastChapter,
    this.wordCount,
    this.updateTime,
    this.canReName,
    this.downloadUrls,
  });

  static Future<BookRuleContext> default_() =>
      RustLib.instance.api.crateApiRuleEngineBookRuleContextDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      bookUrl.hashCode ^
      tocUrl.hashCode ^
      coverUrl.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      wordCount.hashCode ^
      updateTime.hashCode ^
      canReName.hashCode ^
      downloadUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookRuleContext &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          bookUrl == other.bookUrl &&
          tocUrl == other.tocUrl &&
          coverUrl == other.coverUrl &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          wordCount == other.wordCount &&
          updateTime == other.updateTime &&
          canReName == other.canReName &&
          downloadUrls == other.downloadUrls;
}

class Chapter {
  final String name;
  final String url;
  final bool isVolume;
  final bool isVip;
  final bool isPay;
  final String? updateTime;
  final Map<String, String> variables;

  const Chapter({
    required this.name,
    required this.url,
    required this.isVolume,
    required this.isVip,
    required this.isPay,
    this.updateTime,
    required this.variables,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      url.hashCode ^
      isVolume.hashCode ^
      isVip.hashCode ^
      isPay.hashCode ^
      updateTime.hashCode ^
      variables.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          isVolume == other.isVolume &&
          isVip == other.isVip &&
          isPay == other.isPay &&
          updateTime == other.updateTime &&
          variables == other.variables;
}

class ChapterContent {
  final String content;
  final String? title;
  final String? nextUrl;

  const ChapterContent({
    required this.content,
    this.title,
    this.nextUrl,
  });

  @override
  int get hashCode => content.hashCode ^ title.hashCode ^ nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterContent &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          title == other.title &&
          nextUrl == other.nextUrl;
}

class ExploreKindItem {
  final String title;
  final String? url;

  /// Raw JSON of the `style` object when provided by source scripts.
  final String? styleJson;

  const ExploreKindItem({
    required this.title,
    this.url,
    this.styleJson,
  });

  @override
  int get hashCode => title.hashCode ^ url.hashCode ^ styleJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExploreKindItem &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url &&
          styleJson == other.styleJson;
}

class ReviewItem {
  final String? avatar;
  final String content;
  final String? postTime;
  final String? quoteUrl;

  const ReviewItem({
    this.avatar,
    required this.content,
    this.postTime,
    this.quoteUrl,
  });

  @override
  int get hashCode =>
      avatar.hashCode ^
      content.hashCode ^
      postTime.hashCode ^
      quoteUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewItem &&
          runtimeType == other.runtimeType &&
          avatar == other.avatar &&
          content == other.content &&
          postTime == other.postTime &&
          quoteUrl == other.quoteUrl;
}

/// Result of TOC extraction, including the optional next-page URL.
class TocResult {
  final List<Chapter> chapters;

  /// URL of the next TOC page, or `None` if this is the last/only page.
  final String? nextTocUrl;

  const TocResult({
    required this.chapters,
    this.nextTocUrl,
  });

  @override
  int get hashCode => chapters.hashCode ^ nextTocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TocResult &&
          runtimeType == other.runtimeType &&
          chapters == other.chapters &&
          nextTocUrl == other.nextTocUrl;
}
