// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/analyze_url.dart';
import 'api/rule_engine.dart';
import 'dart:async';
import 'dart:convert';
import 'entities/book_source.dart';
import 'entities/rules.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RuleEnginePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine;

  @protected
  RuleEngine
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          dynamic raw);

  @protected
  RuleEngine
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          dynamic raw);

  @protected
  RuleEngine
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, List<String>> dco_decode_Map_String_list_String_None(dynamic raw);

  @protected
  RuleEngine
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnalyzeUrlRequest dco_decode_analyze_url_request(dynamic raw);

  @protected
  AnalyzeUrlResult dco_decode_analyze_url_result(dynamic raw);

  @protected
  BookInfo dco_decode_book_info(dynamic raw);

  @protected
  BookInfoRule dco_decode_book_info_rule(dynamic raw);

  @protected
  BookItem dco_decode_book_item(dynamic raw);

  @protected
  BookRuleContext dco_decode_book_rule_context(dynamic raw);

  @protected
  BookSource dco_decode_book_source(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AnalyzeUrlRequest dco_decode_box_autoadd_analyze_url_request(dynamic raw);

  @protected
  BookInfo dco_decode_box_autoadd_book_info(dynamic raw);

  @protected
  BookInfoRule dco_decode_box_autoadd_book_info_rule(dynamic raw);

  @protected
  BookSource dco_decode_box_autoadd_book_source(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChapterContent dco_decode_box_autoadd_chapter_content(dynamic raw);

  @protected
  ContentRule dco_decode_box_autoadd_content_rule(dynamic raw);

  @protected
  ExploreRule dco_decode_box_autoadd_explore_rule(dynamic raw);

  @protected
  FetchUrlRequest dco_decode_box_autoadd_fetch_url_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  ReviewRule dco_decode_box_autoadd_review_rule(dynamic raw);

  @protected
  SearchRule dco_decode_box_autoadd_search_rule(dynamic raw);

  @protected
  TocRule dco_decode_box_autoadd_toc_rule(dynamic raw);

  @protected
  WebViewRequest dco_decode_box_autoadd_web_view_request(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  ChapterContent dco_decode_chapter_content(dynamic raw);

  @protected
  ContentRule dco_decode_content_rule(dynamic raw);

  @protected
  ExploreKindItem dco_decode_explore_kind_item(dynamic raw);

  @protected
  ExploreRule dco_decode_explore_rule(dynamic raw);

  @protected
  FetchUrlRequest dco_decode_fetch_url_request(dynamic raw);

  @protected
  FetchUrlResult dco_decode_fetch_url_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookItem> dco_decode_list_book_item(dynamic raw);

  @protected
  List<BookSource> dco_decode_list_book_source(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  List<ExploreKindItem> dco_decode_list_explore_kind_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<String>)> dco_decode_list_record_string_list_string(
      dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<ReviewItem> dco_decode_list_review_item(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BookInfo? dco_decode_opt_box_autoadd_book_info(dynamic raw);

  @protected
  BookInfoRule? dco_decode_opt_box_autoadd_book_info_rule(dynamic raw);

  @protected
  BookSource? dco_decode_opt_box_autoadd_book_source(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ChapterContent? dco_decode_opt_box_autoadd_chapter_content(dynamic raw);

  @protected
  ContentRule? dco_decode_opt_box_autoadd_content_rule(dynamic raw);

  @protected
  ExploreRule? dco_decode_opt_box_autoadd_explore_rule(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  ReviewRule? dco_decode_opt_box_autoadd_review_rule(dynamic raw);

  @protected
  SearchRule? dco_decode_opt_box_autoadd_search_rule(dynamic raw);

  @protected
  TocRule? dco_decode_opt_box_autoadd_toc_rule(dynamic raw);

  @protected
  WebViewRequest? dco_decode_opt_box_autoadd_web_view_request(dynamic raw);

  @protected
  (String, List<String>) dco_decode_record_string_list_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  ReviewItem dco_decode_review_item(dynamic raw);

  @protected
  ReviewRule dco_decode_review_rule(dynamic raw);

  @protected
  SearchRule dco_decode_search_rule(dynamic raw);

  @protected
  TocResult dco_decode_toc_result(dynamic raw);

  @protected
  TocRule dco_decode_toc_rule(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebViewRequest dco_decode_web_view_request(dynamic raw);

  @protected
  RuleEngine
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          SseDeserializer deserializer);

  @protected
  RuleEngine
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          SseDeserializer deserializer);

  @protected
  RuleEngine
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  Map<String, List<String>> sse_decode_Map_String_list_String_None(
      SseDeserializer deserializer);

  @protected
  RuleEngine
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnalyzeUrlRequest sse_decode_analyze_url_request(
      SseDeserializer deserializer);

  @protected
  AnalyzeUrlResult sse_decode_analyze_url_result(SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer);

  @protected
  BookInfoRule sse_decode_book_info_rule(SseDeserializer deserializer);

  @protected
  BookItem sse_decode_book_item(SseDeserializer deserializer);

  @protected
  BookRuleContext sse_decode_book_rule_context(SseDeserializer deserializer);

  @protected
  BookSource sse_decode_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AnalyzeUrlRequest sse_decode_box_autoadd_analyze_url_request(
      SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_box_autoadd_book_info(SseDeserializer deserializer);

  @protected
  BookInfoRule sse_decode_box_autoadd_book_info_rule(
      SseDeserializer deserializer);

  @protected
  BookSource sse_decode_box_autoadd_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChapterContent sse_decode_box_autoadd_chapter_content(
      SseDeserializer deserializer);

  @protected
  ContentRule sse_decode_box_autoadd_content_rule(SseDeserializer deserializer);

  @protected
  ExploreRule sse_decode_box_autoadd_explore_rule(SseDeserializer deserializer);

  @protected
  FetchUrlRequest sse_decode_box_autoadd_fetch_url_request(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ReviewRule sse_decode_box_autoadd_review_rule(SseDeserializer deserializer);

  @protected
  SearchRule sse_decode_box_autoadd_search_rule(SseDeserializer deserializer);

  @protected
  TocRule sse_decode_box_autoadd_toc_rule(SseDeserializer deserializer);

  @protected
  WebViewRequest sse_decode_box_autoadd_web_view_request(
      SseDeserializer deserializer);

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  ChapterContent sse_decode_chapter_content(SseDeserializer deserializer);

  @protected
  ContentRule sse_decode_content_rule(SseDeserializer deserializer);

  @protected
  ExploreKindItem sse_decode_explore_kind_item(SseDeserializer deserializer);

  @protected
  ExploreRule sse_decode_explore_rule(SseDeserializer deserializer);

  @protected
  FetchUrlRequest sse_decode_fetch_url_request(SseDeserializer deserializer);

  @protected
  FetchUrlResult sse_decode_fetch_url_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookItem> sse_decode_list_book_item(SseDeserializer deserializer);

  @protected
  List<BookSource> sse_decode_list_book_source(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  List<ExploreKindItem> sse_decode_list_explore_kind_item(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<String>)> sse_decode_list_record_string_list_string(
      SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<ReviewItem> sse_decode_list_review_item(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BookInfo? sse_decode_opt_box_autoadd_book_info(SseDeserializer deserializer);

  @protected
  BookInfoRule? sse_decode_opt_box_autoadd_book_info_rule(
      SseDeserializer deserializer);

  @protected
  BookSource? sse_decode_opt_box_autoadd_book_source(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChapterContent? sse_decode_opt_box_autoadd_chapter_content(
      SseDeserializer deserializer);

  @protected
  ContentRule? sse_decode_opt_box_autoadd_content_rule(
      SseDeserializer deserializer);

  @protected
  ExploreRule? sse_decode_opt_box_autoadd_explore_rule(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ReviewRule? sse_decode_opt_box_autoadd_review_rule(
      SseDeserializer deserializer);

  @protected
  SearchRule? sse_decode_opt_box_autoadd_search_rule(
      SseDeserializer deserializer);

  @protected
  TocRule? sse_decode_opt_box_autoadd_toc_rule(SseDeserializer deserializer);

  @protected
  WebViewRequest? sse_decode_opt_box_autoadd_web_view_request(
      SseDeserializer deserializer);

  @protected
  (String, List<String>) sse_decode_record_string_list_string(
      SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  ReviewItem sse_decode_review_item(SseDeserializer deserializer);

  @protected
  ReviewRule sse_decode_review_rule(SseDeserializer deserializer);

  @protected
  SearchRule sse_decode_search_rule(SseDeserializer deserializer);

  @protected
  TocResult sse_decode_toc_result(SseDeserializer deserializer);

  @protected
  TocRule sse_decode_toc_rule(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebViewRequest sse_decode_web_view_request(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          RuleEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          RuleEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          RuleEngine self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_list_String_None(
      Map<String, List<String>> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          RuleEngine self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_analyze_url_request(
      AnalyzeUrlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_analyze_url_result(
      AnalyzeUrlResult self, SseSerializer serializer);

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_book_info_rule(BookInfoRule self, SseSerializer serializer);

  @protected
  void sse_encode_book_item(BookItem self, SseSerializer serializer);

  @protected
  void sse_encode_book_rule_context(
      BookRuleContext self, SseSerializer serializer);

  @protected
  void sse_encode_book_source(BookSource self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_analyze_url_request(
      AnalyzeUrlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_info(
      BookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_info_rule(
      BookInfoRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_source(
      BookSource self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chapter_content(
      ChapterContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content_rule(
      ContentRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_explore_rule(
      ExploreRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fetch_url_request(
      FetchUrlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_review_rule(
      ReviewRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_rule(
      SearchRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_toc_rule(TocRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_view_request(
      WebViewRequest self, SseSerializer serializer);

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_content(
      ChapterContent self, SseSerializer serializer);

  @protected
  void sse_encode_content_rule(ContentRule self, SseSerializer serializer);

  @protected
  void sse_encode_explore_kind_item(
      ExploreKindItem self, SseSerializer serializer);

  @protected
  void sse_encode_explore_rule(ExploreRule self, SseSerializer serializer);

  @protected
  void sse_encode_fetch_url_request(
      FetchUrlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_fetch_url_result(
      FetchUrlResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_item(List<BookItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_source(
      List<BookSource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_explore_kind_item(
      List<ExploreKindItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_list_string(
      List<(String, List<String>)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_review_item(
      List<ReviewItem> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String_None(
      Map<String, String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_info(
      BookInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_info_rule(
      BookInfoRule? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_source(
      BookSource? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_chapter_content(
      ChapterContent? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_rule(
      ContentRule? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_explore_rule(
      ExploreRule? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_review_rule(
      ReviewRule? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_search_rule(
      SearchRule? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_toc_rule(
      TocRule? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_web_view_request(
      WebViewRequest? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_string(
      (String, List<String>) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_review_item(ReviewItem self, SseSerializer serializer);

  @protected
  void sse_encode_review_rule(ReviewRule self, SseSerializer serializer);

  @protected
  void sse_encode_search_rule(SearchRule self, SseSerializer serializer);

  @protected
  void sse_encode_toc_result(TocResult self, SseSerializer serializer);

  @protected
  void sse_encode_toc_rule(TocRule self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_web_view_request(
      WebViewRequest self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuleEngine(
          int ptr);
}
