// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rules.dart';

/// Mirrors Kotlin `BookSource` — 100% field parity including BaseSource fields.
class BookSource {
  final String bookSourceUrl;
  final String bookSourceName;
  final String? bookSourceGroup;

  /// 0 = text, 1 = audio, 2 = image, 3 = file
  final int bookSourceType;

  /// Regex pattern that matches detail-page URLs for this source.
  final String? bookUrlPattern;
  final int customOrder;
  final bool enabled;
  final bool enabledExplore;

  /// Shared JS library injected into every JS eval context for this source.
  final String? jsLib;

  /// Whether the source uses a managed cookie jar.
  final bool? enabledCookieJar;

  /// Rate-limit string (e.g. "1,1000" = 1 req per 1000 ms).
  final String? concurrentRate;

  /// Custom HTTP headers as a JSON object string `{"Cookie":"..."}`.
  final String? header;

  /// Login page URL (may contain JS template).
  final String? loginUrl;

  /// Login UI layout definition string (JSON describing form fields).
  final String? loginUi;

  /// JS snippet evaluated to verify login state (returns truthy/falsy).
  final String? loginCheckJs;

  /// JS snippet to decrypt/decode cover image bytes.
  final String? coverDecodeJs;
  final String? bookSourceComment;

  /// Human-readable description of what variables this source uses.
  final String? variableComment;
  final PlatformInt64 lastUpdateTime;

  /// Timeout in milliseconds (default 3 minutes, mirrors Kotlin 180000L).
  final PlatformInt64 respondTime;
  final int weight;

  /// URL template for explore/discovery pages (may be multi-line, one per kind).
  final String? exploreUrl;

  /// Explore filter / facet rules (JSON string).
  final String? exploreScreen;
  final ExploreRule? ruleExplore;
  final String? searchUrl;
  final SearchRule? ruleSearch;
  final BookInfoRule? ruleBookInfo;
  final TocRule? ruleToc;
  final ContentRule? ruleContent;

  /// Paragraph-comment rules. Declared for JSON import; not persisted in DB
  /// (mirrors Kotlin's always-null TypeConverter behaviour).
  final ReviewRule? ruleReview;

  const BookSource({
    required this.bookSourceUrl,
    required this.bookSourceName,
    this.bookSourceGroup,
    required this.bookSourceType,
    this.bookUrlPattern,
    required this.customOrder,
    required this.enabled,
    required this.enabledExplore,
    this.jsLib,
    this.enabledCookieJar,
    this.concurrentRate,
    this.header,
    this.loginUrl,
    this.loginUi,
    this.loginCheckJs,
    this.coverDecodeJs,
    this.bookSourceComment,
    this.variableComment,
    required this.lastUpdateTime,
    required this.respondTime,
    required this.weight,
    this.exploreUrl,
    this.exploreScreen,
    this.ruleExplore,
    this.searchUrl,
    this.ruleSearch,
    this.ruleBookInfo,
    this.ruleToc,
    this.ruleContent,
    this.ruleReview,
  });

  @override
  int get hashCode =>
      bookSourceUrl.hashCode ^
      bookSourceName.hashCode ^
      bookSourceGroup.hashCode ^
      bookSourceType.hashCode ^
      bookUrlPattern.hashCode ^
      customOrder.hashCode ^
      enabled.hashCode ^
      enabledExplore.hashCode ^
      jsLib.hashCode ^
      enabledCookieJar.hashCode ^
      concurrentRate.hashCode ^
      header.hashCode ^
      loginUrl.hashCode ^
      loginUi.hashCode ^
      loginCheckJs.hashCode ^
      coverDecodeJs.hashCode ^
      bookSourceComment.hashCode ^
      variableComment.hashCode ^
      lastUpdateTime.hashCode ^
      respondTime.hashCode ^
      weight.hashCode ^
      exploreUrl.hashCode ^
      exploreScreen.hashCode ^
      ruleExplore.hashCode ^
      searchUrl.hashCode ^
      ruleSearch.hashCode ^
      ruleBookInfo.hashCode ^
      ruleToc.hashCode ^
      ruleContent.hashCode ^
      ruleReview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSource &&
          runtimeType == other.runtimeType &&
          bookSourceUrl == other.bookSourceUrl &&
          bookSourceName == other.bookSourceName &&
          bookSourceGroup == other.bookSourceGroup &&
          bookSourceType == other.bookSourceType &&
          bookUrlPattern == other.bookUrlPattern &&
          customOrder == other.customOrder &&
          enabled == other.enabled &&
          enabledExplore == other.enabledExplore &&
          jsLib == other.jsLib &&
          enabledCookieJar == other.enabledCookieJar &&
          concurrentRate == other.concurrentRate &&
          header == other.header &&
          loginUrl == other.loginUrl &&
          loginUi == other.loginUi &&
          loginCheckJs == other.loginCheckJs &&
          coverDecodeJs == other.coverDecodeJs &&
          bookSourceComment == other.bookSourceComment &&
          variableComment == other.variableComment &&
          lastUpdateTime == other.lastUpdateTime &&
          respondTime == other.respondTime &&
          weight == other.weight &&
          exploreUrl == other.exploreUrl &&
          exploreScreen == other.exploreScreen &&
          ruleExplore == other.ruleExplore &&
          searchUrl == other.searchUrl &&
          ruleSearch == other.ruleSearch &&
          ruleBookInfo == other.ruleBookInfo &&
          ruleToc == other.ruleToc &&
          ruleContent == other.ruleContent &&
          ruleReview == other.ruleReview;
}
