// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BookInfoRule {
  final String? init;
  final String? name;
  final String? author;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? updateTime;
  final String? coverUrl;
  final String? tocUrl;
  final String? wordCount;
  final String? canReName;
  final String? downloadUrls;

  const BookInfoRule({
    this.init,
    this.name,
    this.author,
    this.intro,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.coverUrl,
    this.tocUrl,
    this.wordCount,
    this.canReName,
    this.downloadUrls,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      name.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      coverUrl.hashCode ^
      tocUrl.hashCode ^
      wordCount.hashCode ^
      canReName.hashCode ^
      downloadUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfoRule &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          name == other.name &&
          author == other.author &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          coverUrl == other.coverUrl &&
          tocUrl == other.tocUrl &&
          wordCount == other.wordCount &&
          canReName == other.canReName &&
          downloadUrls == other.downloadUrls;
}

class ContentRule {
  final String? content;
  final String? title;
  final String? nextContentUrl;
  final String? webJs;
  final String? sourceRegex;
  final String? replaceRegex;

  /// The replacement string used together with `replace_regex`.
  /// Mirrors Kotlin's `ContentRule.replaceRegex` which stores "regex##replacement".
  /// In our JSON schema we keep them as separate optional fields.
  final String? replaceRegexReplacement;
  final String? imageStyle;
  final String? imageDecode;
  final String? payAction;

  const ContentRule({
    this.content,
    this.title,
    this.nextContentUrl,
    this.webJs,
    this.sourceRegex,
    this.replaceRegex,
    this.replaceRegexReplacement,
    this.imageStyle,
    this.imageDecode,
    this.payAction,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      title.hashCode ^
      nextContentUrl.hashCode ^
      webJs.hashCode ^
      sourceRegex.hashCode ^
      replaceRegex.hashCode ^
      replaceRegexReplacement.hashCode ^
      imageStyle.hashCode ^
      imageDecode.hashCode ^
      payAction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentRule &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          title == other.title &&
          nextContentUrl == other.nextContentUrl &&
          webJs == other.webJs &&
          sourceRegex == other.sourceRegex &&
          replaceRegex == other.replaceRegex &&
          replaceRegexReplacement == other.replaceRegexReplacement &&
          imageStyle == other.imageStyle &&
          imageDecode == other.imageDecode &&
          payAction == other.payAction;
}

/// Mirrors Kotlin `ExploreRule` (implements `BookListRule`).
class ExploreRule {
  final String? bookList;
  final String? name;
  final String? author;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? updateTime;
  final String? bookUrl;
  final String? coverUrl;
  final String? wordCount;

  const ExploreRule({
    this.bookList,
    this.name,
    this.author,
    this.intro,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.bookUrl,
    this.coverUrl,
    this.wordCount,
  });

  @override
  int get hashCode =>
      bookList.hashCode ^
      name.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      bookUrl.hashCode ^
      coverUrl.hashCode ^
      wordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExploreRule &&
          runtimeType == other.runtimeType &&
          bookList == other.bookList &&
          name == other.name &&
          author == other.author &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          bookUrl == other.bookUrl &&
          coverUrl == other.coverUrl &&
          wordCount == other.wordCount;
}

/// Mirrors Kotlin `ReviewRule` — all 10 fields, including WIP ones.
/// Note: in the original Kotlin DB layer the TypeConverter always writes/reads
/// `null` (dead code at persistence layer, live only in JSON import paths).
class ReviewRule {
  final String? reviewUrl;
  final String? avatarRule;
  final String? contentRule;
  final String? postTimeRule;
  final String? reviewQuoteUrl;

  /// WIP — not yet implemented in Kotlin either.
  final String? voteUpUrl;
  final String? voteDownUrl;
  final String? postReviewUrl;
  final String? postQuoteUrl;
  final String? deleteUrl;

  const ReviewRule({
    this.reviewUrl,
    this.avatarRule,
    this.contentRule,
    this.postTimeRule,
    this.reviewQuoteUrl,
    this.voteUpUrl,
    this.voteDownUrl,
    this.postReviewUrl,
    this.postQuoteUrl,
    this.deleteUrl,
  });

  @override
  int get hashCode =>
      reviewUrl.hashCode ^
      avatarRule.hashCode ^
      contentRule.hashCode ^
      postTimeRule.hashCode ^
      reviewQuoteUrl.hashCode ^
      voteUpUrl.hashCode ^
      voteDownUrl.hashCode ^
      postReviewUrl.hashCode ^
      postQuoteUrl.hashCode ^
      deleteUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewRule &&
          runtimeType == other.runtimeType &&
          reviewUrl == other.reviewUrl &&
          avatarRule == other.avatarRule &&
          contentRule == other.contentRule &&
          postTimeRule == other.postTimeRule &&
          reviewQuoteUrl == other.reviewQuoteUrl &&
          voteUpUrl == other.voteUpUrl &&
          voteDownUrl == other.voteDownUrl &&
          postReviewUrl == other.postReviewUrl &&
          postQuoteUrl == other.postQuoteUrl &&
          deleteUrl == other.deleteUrl;
}

/// Mirrors Kotlin `SearchRule` (implements `BookListRule`).
class SearchRule {
  final String? bookList;
  final String? name;
  final String? author;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? updateTime;
  final String? bookUrl;
  final String? tocUrl;
  final String? coverUrl;
  final String? wordCount;
  final String? checkKeyWord;

  const SearchRule({
    this.bookList,
    this.name,
    this.author,
    this.intro,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.bookUrl,
    this.tocUrl,
    this.coverUrl,
    this.wordCount,
    this.checkKeyWord,
  });

  @override
  int get hashCode =>
      bookList.hashCode ^
      name.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      bookUrl.hashCode ^
      tocUrl.hashCode ^
      coverUrl.hashCode ^
      wordCount.hashCode ^
      checkKeyWord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchRule &&
          runtimeType == other.runtimeType &&
          bookList == other.bookList &&
          name == other.name &&
          author == other.author &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          bookUrl == other.bookUrl &&
          tocUrl == other.tocUrl &&
          coverUrl == other.coverUrl &&
          wordCount == other.wordCount &&
          checkKeyWord == other.checkKeyWord;
}

class TocRule {
  final String? preUpdateJs;
  final String? chapterList;
  final String? chapterName;
  final String? chapterUrl;
  final String? formatJs;
  final String? isVolume;
  final String? isVip;
  final String? isPay;
  final String? updateTime;
  final String? nextTocUrl;

  const TocRule({
    this.preUpdateJs,
    this.chapterList,
    this.chapterName,
    this.chapterUrl,
    this.formatJs,
    this.isVolume,
    this.isVip,
    this.isPay,
    this.updateTime,
    this.nextTocUrl,
  });

  @override
  int get hashCode =>
      preUpdateJs.hashCode ^
      chapterList.hashCode ^
      chapterName.hashCode ^
      chapterUrl.hashCode ^
      formatJs.hashCode ^
      isVolume.hashCode ^
      isVip.hashCode ^
      isPay.hashCode ^
      updateTime.hashCode ^
      nextTocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TocRule &&
          runtimeType == other.runtimeType &&
          preUpdateJs == other.preUpdateJs &&
          chapterList == other.chapterList &&
          chapterName == other.chapterName &&
          chapterUrl == other.chapterUrl &&
          formatJs == other.formatJs &&
          isVolume == other.isVolume &&
          isVip == other.isVip &&
          isPay == other.isPay &&
          updateTime == other.updateTime &&
          nextTocUrl == other.nextTocUrl;
}
